build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
                # override:
                #     - command: npm test
                #     coverage:
                #         file: coverage/clover.xml
                #         format: clover
